### ISSUE TITLE
你好，这个可以试用白云校区么？

### ISSUE THREAD

**Issue by jhuqin** [nature2608/jmusupplicant-for-gpnu#1]
打扰了，请问一下，这个白云校区是否能用。谢谢。

**Comment by nature2608** [comment]
可以的。
[https://github.com/BoringCat/minieap-openwrt](url)这个也可以，现在各校区服务名都统一了。
当然，原版mentohust也能用：
源码：https://github.com/nature2608/MentoHUST-OpenWrt-ipk
LUCI：https://github.com/nature2608/luci-app-mentohust
配合luci下界面数据文件选择baiyun即可

**Comment by jhuqin** [comment]
你好，按您说的，我试了，两个项目都不行，不知道什么情况，请问下用mentohust项目，luci界面，里面选项，需要填，哪些。我默认就填了，一个账号和密码。其他都是空的

**Comment by jhuqin** [comment]
现在的锐捷客户端版本是6.85的，不知道有没有影响

**Comment by nature2608** [comment]
我离校前就已经是6.85了，试过都是可以的。minieap和jmusupplicant都是模拟linux客户端进行登录的，需要设置一定的参数才能使用；原版mentohust加上mpf文件即可。

**Comment by jhuqin** [comment]
哦，好的，那我再试下，谢谢

**Comment by jhuqin** [comment]
你好，无试过，还是有报错得地方，要么MAC绑定错误，缺少8021x信息麻烦您看看，是否能看出原因所在。
** 网卡: 	eth0.2
** 网关地址:	10.201.40.1
** 认证超时:	8秒
** 响应间隔:	30秒
** 失败等待:	15秒
** 允许失败:	3次
** 组播地址:	锐捷
** DHCP方式:	认证前
** 数据文件:	/etc/2.mpf
** DHCP脚本:	udhcpc -i
** 本机MAC:	78:a3:51:0c:23:5d
** 使用IP:	10.201.40.40
** 子网掩码:	255.255.248.0
** 认证参数已成功保存到/etc/mentohust.conf.
>> 正在获取IP...
>> 操作结束。
** 本机MAC:	78:a3:51:0c:23:5d
** 使用IP:	10.201.40.40
** 子网掩码:	255.255.248.0
>> 寻找服务器...
** 认证MAC:	00:1a:a9:17:ff:ff
>> 发送用户名...
** 网关MAC:	00:1a:a9:bc:e0:6d
>> 发送密码...
** 客户端版本:	6.85
** MD5种子:	1c:1c:37:67:9e:49:29:17:16:99:6e:3d:bf:fb:ec:aa
!! 缺少8021x.exe信息，客户端校验无法继续！
>> 认证失败!
$$ 系统提示:	用户MAC地址绑定错误!
** 认证MAC:	00:1a:a9:17:ff:ff
>> 发送用户名...
>> 发送密码...
** 客户端版本:	6.85
** MD5种子:	cd:59:a1:27:ae:68:59:11:92:3c:7e:2f:09:a8:4c:11
!! 缺少8021x.exe信息，客户端校验无法继续！
>> 认证失败!
$$ 系统提示:	用户MAC地址绑定错误!
** 认证MAC:	00:1a:a9:17:ff:ff
>> 发送用户名...
>> 发送密码...
** 客户端版本:	6.85
** MD5种子:	46:d6:3a:5f:70:c9:c0:99:6b:35:48:cf:0e:43:a6:e9
!! 缺少8021x.exe信息，客户端校验无法继续！
>> 认证失败!
$$ 系统提示:	用户MAC地址绑定错误!
>> 连续认证失败3次，退出认证。
>> 认证已退出。
enew lease
	USR2	Release lease
/bin/sh: arp: not found

**Comment by nature2608** [comment]
mac地址改成你绑定的mac地址（有线网卡）就行了。

**Comment by jhuqin** [comment]
这个具体在哪里改，还有那个缺少8021x信息，那个是什么意思

**Comment by nature2608** [comment]
op的话在wan口配置里面，老毛子在外网设置

**Comment by jhuqin** [comment]
可以了，谢谢指导。
